export interface Card {
  id: string;
  text: string;
  categoryId: string;
}

export const ANIMAL_CARDS: Card[] = [
  { id: '1', text: 'Lion', categoryId: 'animals' },
  { id: '2', text: 'Elephant', categoryId: 'animals' },
  { id: '3', text: 'Giraffe', categoryId: 'animals' },
  { id: '4', text: 'Monkey', categoryId: 'animals' },
  { id: '5', text: 'Penguin', categoryId: 'animals' },
  { id: '6', text: 'Kangaroo', categoryId: 'animals' },
  { id: '7', text: 'Bear', categoryId: 'animals' },
  { id: '8', text: 'Tiger', categoryId: 'animals' },
  { id: '9', text: 'Zebra', categoryId: 'animals' },
  { id: '10', text: 'Dolphin', categoryId: 'animals' },
  { id: '11', text: 'Shark', categoryId: 'animals' },
  { id: '12', text: 'Eagle', categoryId: 'animals' },
  { id: '13', text: 'Snake', categoryId: 'animals' },
  { id: '14', text: 'Crocodile', categoryId: 'animals' },
  { id: '15', text: 'Flamingo', categoryId: 'animals' },
  { id: '16', text: 'Gorilla', categoryId: 'animals' },
  { id: '17', text: 'Cheetah', categoryId: 'animals' },
  { id: '18', text: 'Hippopotamus', categoryId: 'animals' },
  { id: '19', text: 'Rhinoceros', categoryId: 'animals' },
  { id: '20', text: 'Panda', categoryId: 'animals' },
  { id: '21', text: 'Koala', categoryId: 'animals' },
  { id: '22', text: 'Sloth', categoryId: 'animals' },
  { id: '23', text: 'Octopus', categoryId: 'animals' },
  { id: '24', text: 'Jellyfish', categoryId: 'animals' },
  { id: '25', text: 'Seahorse', categoryId: 'animals' },
  { id: '26', text: 'Butterfly', categoryId: 'animals' },
  { id: '27', text: 'Bee', categoryId: 'animals' },
  { id: '28', text: 'Ladybug', categoryId: 'animals' },
  { id: '29', text: 'Spider', categoryId: 'animals' },
  { id: '30', text: 'Bat', categoryId: 'animals' },
  { id: '31', text: 'Owl', categoryId: 'animals' },
  { id: '32', text: 'Parrot', categoryId: 'animals' },
  { id: '33', text: 'Peacock', categoryId: 'animals' },
  { id: '34', text: 'Turkey', categoryId: 'animals' },
  { id: '35', text: 'Ostrich', categoryId: 'animals' },
  { id: '36', text: 'Camel', categoryId: 'animals' },
  { id: '37', text: 'Horse', categoryId: 'animals' },
  { id: '38', text: 'Pig', categoryId: 'animals' },
  { id: '39', text: 'Sheep', categoryId: 'animals' },
  { id: '40', text: 'Goat', categoryId: 'animals' },
  { id: '41', text: 'Cow', categoryId: 'animals' },
  { id: '42', text: 'Chicken', categoryId: 'animals' },
  { id: '43', text: 'Duck', categoryId: 'animals' },
  { id: '44', text: 'Rabbit', categoryId: 'animals' },
  { id: '45', text: 'Squirrel', categoryId: 'animals' },
  { id: '46', text: 'Raccoon', categoryId: 'animals' },
  { id: '47', text: 'Fox', categoryId: 'animals' },
  { id: '48', text: 'Wolf', categoryId: 'animals' },
  { id: '49', text: 'Deer', categoryId: 'animals' },
  { id: '50', text: 'Moose', categoryId: 'animals' },
];

export const FAMILY_CARDS: Card[] = [
  // Household Items (40 cards)
  { id: '1', text: 'Spoon', categoryId: 'family' },
  { id: '2', text: 'Fork', categoryId: 'family' },
  { id: '3', text: 'Plate', categoryId: 'family' },
  { id: '4', text: 'Cup', categoryId: 'family' },
  { id: '5', text: 'Bowl', categoryId: 'family' },
  { id: '6', text: 'Pillow', categoryId: 'family' },
  { id: '7', text: 'Blanket', categoryId: 'family' },
  { id: '8', text: 'Bed', categoryId: 'family' },
  { id: '9', text: 'Chair', categoryId: 'family' },
  { id: '10', text: 'Table', categoryId: 'family' },
  { id: '11', text: 'Door', categoryId: 'family' },
  { id: '12', text: 'Window', categoryId: 'family' },
  { id: '13', text: 'Lamp', categoryId: 'family' },
  { id: '14', text: 'Mirror', categoryId: 'family' },
  { id: '15', text: 'Clock', categoryId: 'family' },
  { id: '16', text: 'Telephone', categoryId: 'family' },
  { id: '17', text: 'Television', categoryId: 'family' },
  { id: '18', text: 'Broom', categoryId: 'family' },
  { id: '19', text: 'Toothbrush', categoryId: 'family' },
  { id: '20', text: 'Soap', categoryId: 'family' },
  { id: '21', text: 'Towel', categoryId: 'family' },
  { id: '22', text: 'Umbrella', categoryId: 'family' },
  { id: '23', text: 'Key', categoryId: 'family' },
  { id: '24', text: 'Backpack', categoryId: 'family' },
  { id: '25', text: 'Book', categoryId: 'family' },
  { id: '26', text: 'Pen', categoryId: 'family' },
  { id: '27', text: 'Pencil', categoryId: 'family' },
  { id: '28', text: 'Paper', categoryId: 'family' },
  { id: '29', text: 'Scissors', categoryId: 'family' },
  { id: '30', text: 'Glue', categoryId: 'family' },
  { id: '31', text: 'Tape', categoryId: 'family' },
  { id: '32', text: 'Crayon', categoryId: 'family' },
  { id: '33', text: 'Marker', categoryId: 'family' },
  { id: '34', text: 'Computer', categoryId: 'family' },
  { id: '35', text: 'Remote', categoryId: 'family' },
  { id: '36', text: 'Candle', categoryId: 'family' },
  { id: '37', text: 'Picture', categoryId: 'family' },
  { id: '38', text: 'Rug', categoryId: 'family' },
  { id: '39', text: 'Curtain', categoryId: 'family' },
  { id: '40', text: 'Vacuum', categoryId: 'family' },

  // Toys (25 cards)
  { id: '41', text: 'Ball', categoryId: 'family' },
  { id: '42', text: 'Doll', categoryId: 'family' },
  { id: '43', text: 'Teddy bear', categoryId: 'family' },
  { id: '44', text: 'Blocks', categoryId: 'family' },
  { id: '45', text: 'Puzzle', categoryId: 'family' },
  { id: '46', text: 'Balloon', categoryId: 'family' },
  { id: '47', text: 'Kite', categoryId: 'family' },
  { id: '48', text: 'Yo-yo', categoryId: 'family' },
  { id: '49', text: 'Jump rope', categoryId: 'family' },
  { id: '50', text: 'Hula hoop', categoryId: 'family' },
  { id: '51', text: 'Bubbles', categoryId: 'family' },
  { id: '52', text: 'Frisbee', categoryId: 'family' },
  { id: '53', text: 'Skateboard', categoryId: 'family' },
  { id: '54', text: 'Scooter', categoryId: 'family' },
  { id: '55', text: 'Swing', categoryId: 'family' },
  { id: '56', text: 'Slide', categoryId: 'family' },
  { id: '57', text: 'Sandbox', categoryId: 'family' },
  { id: '58', text: 'Trampoline', categoryId: 'family' },
  { id: '59', text: 'Robot', categoryId: 'family' },
  { id: '60', text: 'Drum', categoryId: 'family' },
  { id: '61', text: 'Whistle', categoryId: 'family' },
  { id: '62', text: 'Marble', categoryId: 'family' },
  { id: '63', text: 'Wagon', categoryId: 'family' },
  { id: '64', text: 'Sled', categoryId: 'family' },
  { id: '65', text: 'Shovel', categoryId: 'family' },

  // Vehicles (20 cards)
  { id: '66', text: 'Car', categoryId: 'family' },
  { id: '67', text: 'Truck', categoryId: 'family' },
  { id: '68', text: 'Bus', categoryId: 'family' },
  { id: '69', text: 'Train', categoryId: 'family' },
  { id: '70', text: 'Airplane', categoryId: 'family' },
  { id: '71', text: 'Helicopter', categoryId: 'family' },
  { id: '72', text: 'Boat', categoryId: 'family' },
  { id: '73', text: 'Ship', categoryId: 'family' },
  { id: '74', text: 'Bicycle', categoryId: 'family' },
  { id: '75', text: 'Motorcycle', categoryId: 'family' },
  { id: '76', text: 'Tractor', categoryId: 'family' },
  { id: '77', text: 'Fire truck', categoryId: 'family' },
  { id: '78', text: 'Police car', categoryId: 'family' },
  { id: '79', text: 'Ambulance', categoryId: 'family' },
  { id: '80', text: 'Taxi', categoryId: 'family' },
  { id: '81', text: 'Rocket', categoryId: 'family' },
  { id: '82', text: 'Canoe', categoryId: 'family' },
  { id: '83', text: 'Submarine', categoryId: 'family' },
  { id: '84', text: 'Hot air balloon', categoryId: 'family' },
  { id: '85', text: 'Sailboat', categoryId: 'family' },

  // Food (30 cards)
  { id: '86', text: 'Apple', categoryId: 'family' },
  { id: '87', text: 'Banana', categoryId: 'family' },
  { id: '88', text: 'Orange', categoryId: 'family' },
  { id: '89', text: 'Grapes', categoryId: 'family' },
  { id: '90', text: 'Watermelon', categoryId: 'family' },
  { id: '91', text: 'Strawberry', categoryId: 'family' },
  { id: '92', text: 'Pizza', categoryId: 'family' },
  { id: '93', text: 'Hamburger', categoryId: 'family' },
  { id: '94', text: 'Hot dog', categoryId: 'family' },
  { id: '95', text: 'Sandwich', categoryId: 'family' },
  { id: '96', text: 'Ice cream', categoryId: 'family' },
  { id: '97', text: 'Cookie', categoryId: 'family' },
  { id: '98', text: 'Cake', categoryId: 'family' },
  { id: '99', text: 'Donut', categoryId: 'family' },
  { id: '100', text: 'Bread', categoryId: 'family' },
  { id: '101', text: 'Cheese', categoryId: 'family' },
  { id: '102', text: 'Egg', categoryId: 'family' },
  { id: '103', text: 'Milk', categoryId: 'family' },
  { id: '104', text: 'Juice', categoryId: 'family' },
  { id: '105', text: 'Carrot', categoryId: 'family' },
  { id: '106', text: 'Broccoli', categoryId: 'family' },
  { id: '107', text: 'Corn', categoryId: 'family' },
  { id: '108', text: 'Tomato', categoryId: 'family' },
  { id: '109', text: 'Potato', categoryId: 'family' },
  { id: '110', text: 'Popcorn', categoryId: 'family' },
  { id: '111', text: 'Cereal', categoryId: 'family' },
  { id: '112', text: 'Pancake', categoryId: 'family' },
  { id: '113', text: 'Waffle', categoryId: 'family' },
  { id: '114', text: 'Spaghetti', categoryId: 'family' },
  { id: '115', text: 'Taco', categoryId: 'family' },

  // Nature (25 cards)
  { id: '116', text: 'Tree', categoryId: 'family' },
  { id: '117', text: 'Flower', categoryId: 'family' },
  { id: '118', text: 'Grass', categoryId: 'family' },
  { id: '119', text: 'Sun', categoryId: 'family' },
  { id: '120', text: 'Moon', categoryId: 'family' },
  { id: '121', text: 'Star', categoryId: 'family' },
  { id: '122', text: 'Cloud', categoryId: 'family' },
  { id: '123', text: 'Rainbow', categoryId: 'family' },
  { id: '124', text: 'Rain', categoryId: 'family' },
  { id: '125', text: 'Snow', categoryId: 'family' },
  { id: '126', text: 'Wind', categoryId: 'family' },
  { id: '127', text: 'Mountain', categoryId: 'family' },
  { id: '128', text: 'River', categoryId: 'family' },
  { id: '129', text: 'Lake', categoryId: 'family' },
  { id: '130', text: 'Ocean', categoryId: 'family' },
  { id: '131', text: 'Beach', categoryId: 'family' },
  { id: '132', text: 'Rock', categoryId: 'family' },
  { id: '133', text: 'Sand', categoryId: 'family' },
  { id: '134', text: 'Shell', categoryId: 'family' },
  { id: '135', text: 'Leaf', categoryId: 'family' },
  { id: '136', text: 'Acorn', categoryId: 'family' },
  { id: '137', text: 'Nest', categoryId: 'family' },
  { id: '138', text: 'Garden', categoryId: 'family' },
  { id: '139', text: 'Park', categoryId: 'family' },
  { id: '140', text: 'Forest', categoryId: 'family' },

  // Clothing (20 cards)
  { id: '141', text: 'Hat', categoryId: 'family' },
  { id: '142', text: 'Shirt', categoryId: 'family' },
  { id: '143', text: 'Pants', categoryId: 'family' },
  { id: '144', text: 'Dress', categoryId: 'family' },
  { id: '145', text: 'Skirt', categoryId: 'family' },
  { id: '146', text: 'Shoes', categoryId: 'family' },
  { id: '147', text: 'Socks', categoryId: 'family' },
  { id: '148', text: 'Coat', categoryId: 'family' },
  { id: '149', text: 'Jacket', categoryId: 'family' },
  { id: '150', text: 'Sweater', categoryId: 'family' },
  { id: '151', text: 'Scarf', categoryId: 'family' },
  { id: '152', text: 'Gloves', categoryId: 'family' },
  { id: '153', text: 'Boots', categoryId: 'family' },
  { id: '154', text: 'Sandals', categoryId: 'family' },
  { id: '155', text: 'Pajamas', categoryId: 'family' },
  { id: '156', text: 'Belt', categoryId: 'family' },
  { id: '157', text: 'Tie', categoryId: 'family' },
  { id: '158', text: 'Sunglasses', categoryId: 'family' },
  { id: '159', text: 'Glasses', categoryId: 'family' },
  { id: '160', text: 'Crown', categoryId: 'family' },

  // Misc Objects (20 cards)
  { id: '161', text: 'Guitar', categoryId: 'family' },
  { id: '162', text: 'Piano', categoryId: 'family' },
  { id: '163', text: 'Camera', categoryId: 'family' },
  { id: '164', text: 'Microphone', categoryId: 'family' },
  { id: '165', text: 'Trophy', categoryId: 'family' },
  { id: '166', text: 'Medal', categoryId: 'family' },
  { id: '167', text: 'Flag', categoryId: 'family' },
  { id: '168', text: 'Map', categoryId: 'family' },
  { id: '169', text: 'Compass', categoryId: 'family' },
  { id: '170', text: 'Flashlight', categoryId: 'family' },
  { id: '171', text: 'Tent', categoryId: 'family' },
  { id: '172', text: 'Campfire', categoryId: 'family' },
  { id: '173', text: 'Ladder', categoryId: 'family' },
  { id: '174', text: 'Hammer', categoryId: 'family' },
  { id: '175', text: 'Mailbox', categoryId: 'family' },
  { id: '176', text: 'Gift', categoryId: 'family' },
  { id: '177', text: 'Crown', categoryId: 'family' },
  { id: '178', text: 'Magic wand', categoryId: 'family' },
  { id: '179', text: 'Castle', categoryId: 'family' },
  { id: '180', text: 'Bridge', categoryId: 'family' },

  // Actions - Daily Activities (20 cards)
  { id: '181', text: 'Eating', categoryId: 'family' },
  { id: '182', text: 'Drinking', categoryId: 'family' },
  { id: '183', text: 'Sleeping', categoryId: 'family' },
  { id: '184', text: 'Waking up', categoryId: 'family' },
  { id: '185', text: 'Brushing teeth', categoryId: 'family' },
  { id: '186', text: 'Combing hair', categoryId: 'family' },
  { id: '187', text: 'Getting dressed', categoryId: 'family' },
  { id: '188', text: 'Taking a bath', categoryId: 'family' },
  { id: '189', text: 'Washing hands', categoryId: 'family' },
  { id: '190', text: 'Cooking', categoryId: 'family' },
  { id: '191', text: 'Cleaning', categoryId: 'family' },
  { id: '192', text: 'Reading', categoryId: 'family' },
  { id: '193', text: 'Writing', categoryId: 'family' },
  { id: '194', text: 'Drawing', categoryId: 'family' },
  { id: '195', text: 'Painting', categoryId: 'family' },
  { id: '196', text: 'Cutting', categoryId: 'family' },
  { id: '197', text: 'Gluing', categoryId: 'family' },
  { id: '198', text: 'Talking', categoryId: 'family' },
  { id: '199', text: 'Listening', categoryId: 'family' },
  { id: '200', text: 'Thinking', categoryId: 'family' },

  // Actions - Play & Movement (25 cards)
  { id: '201', text: 'Running', categoryId: 'family' },
  { id: '202', text: 'Walking', categoryId: 'family' },
  { id: '203', text: 'Jumping', categoryId: 'family' },
  { id: '204', text: 'Hopping', categoryId: 'family' },
  { id: '205', text: 'Skipping', categoryId: 'family' },
  { id: '206', text: 'Dancing', categoryId: 'family' },
  { id: '207', text: 'Spinning', categoryId: 'family' },
  { id: '208', text: 'Twirling', categoryId: 'family' },
  { id: '209', text: 'Crawling', categoryId: 'family' },
  { id: '210', text: 'Climbing', categoryId: 'family' },
  { id: '211', text: 'Swimming', categoryId: 'family' },
  { id: '212', text: 'Flying', categoryId: 'family' },
  { id: '213', text: 'Sliding', categoryId: 'family' },
  { id: '214', text: 'Swinging', categoryId: 'family' },
  { id: '215', text: 'Balancing', categoryId: 'family' },
  { id: '216', text: 'Marching', categoryId: 'family' },
  { id: '217', text: 'Tiptoing', categoryId: 'family' },
  { id: '218', text: 'Stretching', categoryId: 'family' },
  { id: '219', text: 'Bending', categoryId: 'family' },
  { id: '220', text: 'Reaching', categoryId: 'family' },
  { id: '221', text: 'Clapping', categoryId: 'family' },
  { id: '222', text: 'Stomping', categoryId: 'family' },
  { id: '223', text: 'Kicking', categoryId: 'family' },
  { id: '224', text: 'Throwing', categoryId: 'family' },
  { id: '225', text: 'Catching', categoryId: 'family' },

  // Actions - Emotions & Expressions (15 cards)
  { id: '226', text: 'Smiling', categoryId: 'family' },
  { id: '227', text: 'Laughing', categoryId: 'family' },
  { id: '228', text: 'Giggling', categoryId: 'family' },
  { id: '229', text: 'Crying', categoryId: 'family' },
  { id: '230', text: 'Yawning', categoryId: 'family' },
  { id: '231', text: 'Sneezing', categoryId: 'family' },
  { id: '232', text: 'Coughing', categoryId: 'family' },
  { id: '233', text: 'Waving', categoryId: 'family' },
  { id: '234', text: 'Hugging', categoryId: 'family' },
  { id: '235', text: 'Kissing', categoryId: 'family' },
  { id: '236', text: 'Blowing', categoryId: 'family' },
  { id: '237', text: 'Whistling', categoryId: 'family' },
  { id: '238', text: 'Singing', categoryId: 'family' },
  { id: '239', text: 'Whispering', categoryId: 'family' },
  { id: '240', text: 'Shouting', categoryId: 'family' },

  // Actions - Animal & Misc (10 cards)
  { id: '241', text: 'Barking', categoryId: 'family' },
  { id: '242', text: 'Meowing', categoryId: 'family' },
  { id: '243', text: 'Roaring', categoryId: 'family' },
  { id: '244', text: 'Chirping', categoryId: 'family' },
  { id: '245', text: 'Buzzing', categoryId: 'family' },
  { id: '246', text: 'Digging', categoryId: 'family' },
  { id: '247', text: 'Planting', categoryId: 'family' },
  { id: '248', text: 'Watering', categoryId: 'family' },
  { id: '249', text: 'Building', categoryId: 'family' },
  { id: '250', text: 'Helping', categoryId: 'family' },
];

export const getCardsByCategory = (categoryId: string): Card[] => {
  switch (categoryId) {
    case 'animals':
      return ANIMAL_CARDS;
    case 'family':
      return FAMILY_CARDS;
    default:
      return [];
  }
};

export const shuffleCards = (cards: Card[]): Card[] => {
  const shuffled = [...cards];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};
