export interface Card {
  id: string;
  text: string;
  categoryId: string;
  svgData?: string; // Optional inline SVG string for visual representation
}

export const ANIMAL_CARDS: Card[] = [
  { id: '1', text: 'Lion', categoryId: 'animals' },
  { id: '2', text: 'Elephant', categoryId: 'animals' },
  { id: '3', text: 'Giraffe', categoryId: 'animals' },
  { id: '4', text: 'Monkey', categoryId: 'animals' },
  { id: '5', text: 'Penguin', categoryId: 'animals' },
  { id: '6', text: 'Kangaroo', categoryId: 'animals' },
  { id: '7', text: 'Bear', categoryId: 'animals' },
  { id: '8', text: 'Tiger', categoryId: 'animals' },
  { id: '9', text: 'Zebra', categoryId: 'animals' },
  { id: '10', text: 'Dolphin', categoryId: 'animals' },
  { id: '11', text: 'Shark', categoryId: 'animals' },
  { id: '12', text: 'Eagle', categoryId: 'animals' },
  { id: '13', text: 'Snake', categoryId: 'animals' },
  { id: '14', text: 'Crocodile', categoryId: 'animals' },
  { id: '15', text: 'Flamingo', categoryId: 'animals' },
  { id: '16', text: 'Gorilla', categoryId: 'animals' },
  { id: '17', text: 'Cheetah', categoryId: 'animals' },
  { id: '18', text: 'Hippopotamus', categoryId: 'animals' },
  { id: '19', text: 'Rhinoceros', categoryId: 'animals' },
  { id: '20', text: 'Panda', categoryId: 'animals' },
  { id: '21', text: 'Koala', categoryId: 'animals' },
  { id: '22', text: 'Sloth', categoryId: 'animals' },
  { id: '23', text: 'Octopus', categoryId: 'animals' },
  { id: '24', text: 'Jellyfish', categoryId: 'animals' },
  { id: '25', text: 'Seahorse', categoryId: 'animals' },
  { id: '26', text: 'Butterfly', categoryId: 'animals' },
  { id: '27', text: 'Bee', categoryId: 'animals' },
  { id: '28', text: 'Ladybug', categoryId: 'animals' },
  { id: '29', text: 'Spider', categoryId: 'animals' },
  { id: '30', text: 'Bat', categoryId: 'animals' },
  { id: '31', text: 'Owl', categoryId: 'animals' },
  { id: '32', text: 'Parrot', categoryId: 'animals' },
  { id: '33', text: 'Peacock', categoryId: 'animals' },
  { id: '34', text: 'Turkey', categoryId: 'animals' },
  { id: '35', text: 'Ostrich', categoryId: 'animals' },
  { id: '36', text: 'Camel', categoryId: 'animals' },
  { id: '37', text: 'Horse', categoryId: 'animals' },
  { id: '38', text: 'Pig', categoryId: 'animals' },
  { id: '39', text: 'Sheep', categoryId: 'animals' },
  { id: '40', text: 'Goat', categoryId: 'animals' },
  { id: '41', text: 'Cow', categoryId: 'animals' },
  { id: '42', text: 'Chicken', categoryId: 'animals' },
  { id: '43', text: 'Duck', categoryId: 'animals' },
  { id: '44', text: 'Rabbit', categoryId: 'animals' },
  { id: '45', text: 'Squirrel', categoryId: 'animals' },
  { id: '46', text: 'Raccoon', categoryId: 'animals' },
  { id: '47', text: 'Fox', categoryId: 'animals' },
  { id: '48', text: 'Wolf', categoryId: 'animals' },
  { id: '49', text: 'Deer', categoryId: 'animals' },
  { id: '50', text: 'Moose', categoryId: 'animals' },
];

export const FAMILY_CARDS: Card[] = [
  // Household Items (40 cards)
  { id: '1', text: 'Spoon', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:spoon.svg?color=white&width=100&height=100' },
  { id: '2', text: 'Fork', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:fork-and-knife.svg?color=white&width=100&height=100' },
  { id: '3', text: 'Plate', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:plate.svg?color=white&width=100&height=100' },
  { id: '4', text: 'Cup', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cup-with-straw.svg?color=white&width=100&height=100' },
  { id: '5', text: 'Bowl', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:bowl-with-spoon.svg?color=white&width=100&height=100' },
  { id: '6', text: 'Pillow', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:pillow.svg?color=white&width=100&height=100' },
  { id: '7', text: 'Blanket', categoryId: 'family', svgData: 'https://api.iconify.design/noto:blanket.svg?color=white&width=100&height=100' },
  { id: '8', text: 'Bed', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:bed.svg?color=white&width=100&height=100' },
  { id: '9', text: 'Chair', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:chair.svg?color=white&width=100&height=100' },
  { id: '10', text: 'Table', categoryId: 'family', svgData: 'https://api.iconify.design/noto:card-index-dividers.svg?color=white&width=100&height=100' },
  { id: '11', text: 'Door', categoryId: 'family', svgData: 'https://api.iconify.design/noto:door.svg?color=white&width=100&height=100' },
  { id: '12', text: 'Window', categoryId: 'family', svgData: 'https://api.iconify.design/noto:window.svg?color=white&width=100&height=100' },
  { id: '13', text: 'Lamp', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:lamp.svg?color=white&width=100&height=100' },
  { id: '14', text: 'Mirror', categoryId: 'family', svgData: 'https://api.iconify.design/noto:mirror.svg?color=white&width=100&height=100' },
  { id: '15', text: 'Clock', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:alarm-clock.svg?color=white&width=100&height=100' },
  { id: '16', text: 'Telephone', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:telephone.svg?color=white&width=100&height=100' },
  { id: '17', text: 'Television', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:television.svg?color=white&width=100&height=100' },
  { id: '18', text: 'Broom', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:broom.svg?color=white&width=100&height=100' },
  { id: '19', text: 'Toothbrush', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:toothbrush.svg?color=white&width=100&height=100' },
  { id: '20', text: 'Soap', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:soap.svg?color=white&width=100&height=100' },
  { id: '21', text: 'Towel', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:towel.svg?color=white&width=100&height=100' },
  { id: '22', text: 'Umbrella', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:umbrella.svg?color=white&width=100&height=100' },
  { id: '23', text: 'Key', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:key.svg?color=white&width=100&height=100' },
  { id: '24', text: 'Backpack', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:backpack.svg?color=white&width=100&height=100' },
  { id: '25', text: 'Book', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:books.svg?color=white&width=100&height=100' },
  { id: '26', text: 'Pen', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:pen.svg?color=white&width=100&height=100' },
  { id: '27', text: 'Pencil', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:pencil.svg?color=white&width=100&height=100' },
  { id: '28', text: 'Paper', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:page-facing-up.svg?color=white&width=100&height=100' },
  { id: '29', text: 'Scissors', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:scissors.svg?color=white&width=100&height=100' },
  { id: '30', text: 'Glue', categoryId: 'family', svgData: 'https://api.iconify.design/noto:adhesive-bandage.svg?color=white&width=100&height=100' },
  { id: '31', text: 'Tape', categoryId: 'family', svgData: 'https://api.iconify.design/noto:roll-of-paper.svg?color=white&width=100&height=100' },
  { id: '32', text: 'Crayon', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:crayon.svg?color=white&width=100&height=100' },
  { id: '33', text: 'Marker', categoryId: 'family', svgData: 'https://api.iconify.design/noto:lower-left-fountain-pen.svg?color=white&width=100&height=100' },
  { id: '34', text: 'Computer', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:laptop.svg?color=white&width=100&height=100' },
  { id: '35', text: 'Remote', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:television.svg?color=white&width=100&height=100' },
  { id: '36', text: 'Candle', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:candle.svg?color=white&width=100&height=100' },
  { id: '37', text: 'Picture', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:framed-picture.svg?color=white&width=100&height=100' },
  { id: '38', text: 'Rug', categoryId: 'family', svgData: 'https://api.iconify.design/noto:rug.svg?color=white&width=100&height=100' },
  { id: '39', text: 'Curtain', categoryId: 'family', svgData: 'https://api.iconify.design/noto:window.svg?color=white&width=100&height=100' },
  { id: '40', text: 'Vacuum', categoryId: 'family', svgData: 'https://api.iconify.design/noto:broom.svg?color=white&width=100&height=100' },
  { id: '41', text: 'Ball', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:soccer-ball.svg?color=white&width=100&height=100' },
  { id: '42', text: 'Doll', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:doll.svg?color=white&width=100&height=100' },
  { id: '43', text: 'Teddy bear', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:teddy-bear.svg?color=white&width=100&height=100' },
  { id: '44', text: 'Blocks', categoryId: 'family', svgData: 'https://api.iconify.design/noto:building-construction.svg?color=white&width=100&height=100' },
  { id: '45', text: 'Puzzle', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:puzzle-piece.svg?color=white&width=100&height=100' },
  { id: '46', text: 'Balloon', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:balloon.svg?color=white&width=100&height=100' },
  { id: '47', text: 'Kite', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:kite.svg?color=white&width=100&height=100' },
  { id: '48', text: 'Yo-yo', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:yo-yo.svg?color=white&width=100&height=100' },
  { id: '49', text: 'Jump rope', categoryId: 'family', svgData: 'https://api.iconify.design/noto:jumping.svg?color=white&width=100&height=100' },
  { id: '50', text: 'Hula hoop', categoryId: 'family', svgData: 'https://api.iconify.design/noto:person-cartwheeling.svg?color=white&width=100&height=100' },
  { id: '51', text: 'Bubbles', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:soap.svg?color=white&width=100&height=100' },
  { id: '52', text: 'Frisbee', categoryId: 'family', svgData: 'https://api.iconify.design/noto:flying-disc.svg?color=white&width=100&height=100' },
  { id: '53', text: 'Skateboard', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:skateboard.svg?color=white&width=100&height=100' },
  { id: '54', text: 'Scooter', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:kick-scooter.svg?color=white&width=100&height=100' },
  { id: '55', text: 'Swing', categoryId: 'family', svgData: 'https://api.iconify.design/noto:person-on-swings.svg?color=white&width=100&height=100' },
  { id: '56', text: 'Slide', categoryId: 'family', svgData: 'https://api.iconify.design/noto:playground-slide.svg?color=white&width=100&height=100' },
  { id: '57', text: 'Sandbox', categoryId: 'family', svgData: 'https://api.iconify.design/noto:desert.svg?color=white&width=100&height=100' },
  { id: '58', text: 'Trampoline', categoryId: 'family', svgData: 'https://api.iconify.design/noto:person-bouncing-ball.svg?color=white&width=100&height=100' },
  { id: '59', text: 'Robot', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:robot.svg?color=white&width=100&height=100' },
  { id: '60', text: 'Drum', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:drum.svg?color=white&width=100&height=100' },
  { id: '61', text: 'Whistle', categoryId: 'family', svgData: 'https://api.iconify.design/noto:whistle.svg?color=white&width=100&height=100' },
  { id: '62', text: 'Marble', categoryId: 'family', svgData: 'https://api.iconify.design/noto:red-circle.svg?color=white&width=100&height=100' },
  { id: '63', text: 'Wagon', categoryId: 'family', svgData: 'https://api.iconify.design/noto:articulated-lorry.svg?color=white&width=100&height=100' },
  { id: '64', text: 'Sled', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sled.svg?color=white&width=100&height=100' },
  { id: '65', text: 'Shovel', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:shovel.svg?color=white&width=100&height=100' },
  { id: '66', text: 'Car', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:automobile.svg?color=white&width=100&height=100' },
  { id: '67', text: 'Truck', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:delivery-truck.svg?color=white&width=100&height=100' },
  { id: '68', text: 'Bus', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:bus.svg?color=white&width=100&height=100' },
  { id: '69', text: 'Train', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:locomotive.svg?color=white&width=100&height=100' },
  { id: '70', text: 'Airplane', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:airplane.svg?color=white&width=100&height=100' },
  { id: '71', text: 'Helicopter', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:helicopter.svg?color=white&width=100&height=100' },
  { id: '72', text: 'Boat', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sailboat.svg?color=white&width=100&height=100' },
  { id: '73', text: 'Ship', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:ship.svg?color=white&width=100&height=100' },
  { id: '74', text: 'Bicycle', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:bicycle.svg?color=white&width=100&height=100' },
  { id: '75', text: 'Motorcycle', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:motorcycle.svg?color=white&width=100&height=100' },
  { id: '76', text: 'Tractor', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:tractor.svg?color=white&width=100&height=100' },
  { id: '77', text: 'Fire truck', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:fire-engine.svg?color=white&width=100&height=100' },
  { id: '78', text: 'Police car', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:police-car.svg?color=white&width=100&height=100' },
  { id: '79', text: 'Ambulance', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:ambulance.svg?color=white&width=100&height=100' },
  { id: '80', text: 'Taxi', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:taxi.svg?color=white&width=100&height=100' },
  { id: '81', text: 'Rocket', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:rocket.svg?color=white&width=100&height=100' },
  { id: '82', text: 'Canoe', categoryId: 'family', svgData: 'https://api.iconify.design/noto:canoe.svg?color=white&width=100&height=100' },
  { id: '83', text: 'Submarine', categoryId: 'family', svgData: 'https://api.iconify.design/noto:submarine.svg?color=white&width=100&height=100' },
  { id: '84', text: 'Hot air balloon', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:hot-air-balloon.svg?color=white&width=100&height=100' },
  { id: '85', text: 'Sailboat', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sailboat.svg?color=white&width=100&height=100' },
  { id: '86', text: 'Apple', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:red-apple.svg?color=white&width=100&height=100' },
  { id: '87', text: 'Banana', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:banana.svg?color=white&width=100&height=100' },
  { id: '88', text: 'Orange', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:tangerine.svg?color=white&width=100&height=100' },
  { id: '89', text: 'Grapes', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:grapes.svg?color=white&width=100&height=100' },
  { id: '90', text: 'Watermelon', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:watermelon.svg?color=white&width=100&height=100' },
  { id: '91', text: 'Strawberry', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:strawberry.svg?color=white&width=100&height=100' },
  { id: '92', text: 'Pizza', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:pizza.svg?color=white&width=100&height=100' },
  { id: '93', text: 'Hamburger', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:hamburger.svg?color=white&width=100&height=100' },
  { id: '94', text: 'Hot dog', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:hot-dog.svg?color=white&width=100&height=100' },
  { id: '95', text: 'Sandwich', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sandwich.svg?color=white&width=100&height=100' },
  { id: '96', text: 'Ice cream', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:ice-cream.svg?color=white&width=100&height=100' },
  { id: '97', text: 'Cookie', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cookie.svg?color=white&width=100&height=100' },
  { id: '98', text: 'Cake', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:birthday-cake.svg?color=white&width=100&height=100' },
  { id: '99', text: 'Donut', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:doughnut.svg?color=white&width=100&height=100' },
  { id: '100', text: 'Bread', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:bread.svg?color=white&width=100&height=100' },
  { id: '101', text: 'Cheese', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cheese-wedge.svg?color=white&width=100&height=100' },
  { id: '102', text: 'Egg', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:egg.svg?color=white&width=100&height=100' },
  { id: '103', text: 'Milk', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:glass-of-milk.svg?color=white&width=100&height=100' },
  { id: '104', text: 'Juice', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:beverage-box.svg?color=white&width=100&height=100' },
  { id: '105', text: 'Carrot', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:carrot.svg?color=white&width=100&height=100' },
  { id: '106', text: 'Broccoli', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:broccoli.svg?color=white&width=100&height=100' },
  { id: '107', text: 'Corn', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:ear-of-corn.svg?color=white&width=100&height=100' },
  { id: '108', text: 'Tomato', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:tomato.svg?color=white&width=100&height=100' },
  { id: '109', text: 'Potato', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:potato.svg?color=white&width=100&height=100' },
  { id: '110', text: 'Popcorn', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:popcorn.svg?color=white&width=100&height=100' },
  { id: '111', text: 'Cereal', categoryId: 'family', svgData: 'https://api.iconify.design/noto:bowl-with-spoon.svg?color=white&width=100&height=100' },
  { id: '112', text: 'Pancake', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:pancakes.svg?color=white&width=100&height=100' },
  { id: '113', text: 'Waffle', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:waffle.svg?color=white&width=100&height=100' },
  { id: '114', text: 'Spaghetti', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:spaghetti.svg?color=white&width=100&height=100' },
  { id: '115', text: 'Taco', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:taco.svg?color=white&width=100&height=100' },
  { id: '116', text: 'Tree', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:deciduous-tree.svg?color=white&width=100&height=100' },
  { id: '117', text: 'Flower', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cherry-blossom.svg?color=white&width=100&height=100' },
  { id: '118', text: 'Grass', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sheaf-of-rice.svg?color=white&width=100&height=100' },
  { id: '119', text: 'Sun', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sun.svg?color=white&width=100&height=100' },
  { id: '120', text: 'Moon', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:crescent-moon.svg?color=white&width=100&height=100' },
  { id: '121', text: 'Star', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:star.svg?color=white&width=100&height=100' },
  { id: '122', text: 'Cloud', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cloud.svg?color=white&width=100&height=100' },
  { id: '123', text: 'Rainbow', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:rainbow.svg?color=white&width=100&height=100' },
  { id: '124', text: 'Rain', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cloud-with-rain.svg?color=white&width=100&height=100' },
  { id: '125', text: 'Snow', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:snowflake.svg?color=white&width=100&height=100' },
  { id: '126', text: 'Wind', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:wind-face.svg?color=white&width=100&height=100' },
  { id: '127', text: 'Mountain', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:mountain.svg?color=white&width=100&height=100' },
  { id: '128', text: 'River', categoryId: 'family', svgData: 'https://api.iconify.design/noto:water-wave.svg?color=white&width=100&height=100' },
  { id: '129', text: 'Lake', categoryId: 'family', svgData: 'https://api.iconify.design/noto:water-wave.svg?color=white&width=100&height=100' },
  { id: '130', text: 'Ocean', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:water-wave.svg?color=white&width=100&height=100' },
  { id: '131', text: 'Beach', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:beach-with-umbrella.svg?color=white&width=100&height=100' },
  { id: '132', text: 'Rock', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:rock.svg?color=white&width=100&height=100' },
  { id: '133', text: 'Sand', categoryId: 'family', svgData: 'https://api.iconify.design/noto:desert-island.svg?color=white&width=100&height=100' },
  { id: '134', text: 'Shell', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:spiral-shell.svg?color=white&width=100&height=100' },
  { id: '135', text: 'Leaf', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:leaf-fluttering-in-wind.svg?color=white&width=100&height=100' },
  { id: '136', text: 'Acorn', categoryId: 'family', svgData: 'https://api.iconify.design/noto:chestnut.svg?color=white&width=100&height=100' },
  { id: '137', text: 'Nest', categoryId: 'family', svgData: 'https://api.iconify.design/noto:bird.svg?color=white&width=100&height=100' },
  { id: '138', text: 'Garden', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:potted-plant.svg?color=white&width=100&height=100' },
  { id: '139', text: 'Park', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:park.svg?color=white&width=100&height=100' },
  { id: '140', text: 'Forest', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:evergreen-tree.svg?color=white&width=100&height=100' },
  { id: '141', text: 'Hat', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:top-hat.svg?color=white&width=100&height=100' },
  { id: '142', text: 'Shirt', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:t-shirt.svg?color=white&width=100&height=100' },
  { id: '143', text: 'Pants', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:jeans.svg?color=white&width=100&height=100' },
  { id: '144', text: 'Dress', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:dress.svg?color=white&width=100&height=100' },
  { id: '145', text: 'Skirt', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:skirt.svg?color=white&width=100&height=100' },
  { id: '146', text: 'Shoes', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:running-shoe.svg?color=white&width=100&height=100' },
  { id: '147', text: 'Socks', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:socks.svg?color=white&width=100&height=100' },
  { id: '148', text: 'Coat', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:coat.svg?color=white&width=100&height=100' },
  { id: '149', text: 'Jacket', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:womans-clothes.svg?color=white&width=100&height=100' },
  { id: '150', text: 'Sweater', categoryId: 'family', svgData: 'https://api.iconify.design/noto:yarn.svg?color=white&width=100&height=100' },
  { id: '151', text: 'Scarf', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:scarf.svg?color=white&width=100&height=100' },
  { id: '152', text: 'Gloves', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:gloves.svg?color=white&width=100&height=100' },
  { id: '153', text: 'Boots', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:womans-boots.svg?color=white&width=100&height=100' },
  { id: '154', text: 'Sandals', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:thong-sandal.svg?color=white&width=100&height=100' },
  { id: '155', text: 'Pajamas', categoryId: 'family', svgData: 'https://api.iconify.design/noto:person-in-bed.svg?color=white&width=100&height=100' },
  { id: '156', text: 'Belt', categoryId: 'family', svgData: 'https://api.iconify.design/noto:gear.svg?color=white&width=100&height=100' },
  { id: '157', text: 'Tie', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:necktie.svg?color=white&width=100&height=100' },
  { id: '158', text: 'Sunglasses', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sunglasses.svg?color=white&width=100&height=100' },
  { id: '159', text: 'Glasses', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:glasses.svg?color=white&width=100&height=100' },
  { id: '160', text: 'Crown', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:crown.svg?color=white&width=100&height=100' },
  { id: '161', text: 'Guitar', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:guitar.svg?color=white&width=100&height=100' },
  { id: '162', text: 'Piano', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:musical-keyboard.svg?color=white&width=100&height=100' },
  { id: '163', text: 'Camera', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:camera.svg?color=white&width=100&height=100' },
  { id: '164', text: 'Microphone', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:microphone.svg?color=white&width=100&height=100' },
  { id: '165', text: 'Trophy', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:trophy.svg?color=white&width=100&height=100' },
  { id: '166', text: 'Medal', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sports-medal.svg?color=white&width=100&height=100' },
  { id: '167', text: 'Flag', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:triangular-flag.svg?color=white&width=100&height=100' },
  { id: '168', text: 'Map', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:world-map.svg?color=white&width=100&height=100' },
  { id: '169', text: 'Compass', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:compass.svg?color=white&width=100&height=100' },
  { id: '170', text: 'Flashlight', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:flashlight.svg?color=white&width=100&height=100' },
  { id: '171', text: 'Tent', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:tent.svg?color=white&width=100&height=100' },
  { id: '172', text: 'Campfire', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:fire.svg?color=white&width=100&height=100' },
  { id: '173', text: 'Ladder', categoryId: 'family', svgData: 'https://api.iconify.design/noto:ladder.svg?color=white&width=100&height=100' },
  { id: '174', text: 'Hammer', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:hammer.svg?color=white&width=100&height=100' },
  { id: '175', text: 'Mailbox', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:mailbox.svg?color=white&width=100&height=100' },
  { id: '176', text: 'Gift', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:wrapped-gift.svg?color=white&width=100&height=100' },
  { id: '177', text: 'Crown', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:crown.svg?color=white&width=100&height=100' },
  { id: '178', text: 'Magic wand', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:magic-wand.svg?color=white&width=100&height=100' },
  { id: '179', text: 'Castle', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:european-castle.svg?color=white&width=100&height=100' },
  { id: '180', text: 'Bridge', categoryId: 'family', svgData: 'https://api.iconify.design/noto:bridge-at-night.svg?color=white&width=100&height=100' },
  { id: '181', text: 'Eating', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:fork-and-knife-with-plate.svg?color=white&width=100&height=100' },
  { id: '182', text: 'Drinking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cup-with-straw.svg?color=white&width=100&height=100' },
  { id: '183', text: 'Sleeping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sleeping-face.svg?color=white&width=100&height=100' },
  { id: '184', text: 'Waking up', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:yawning-face.svg?color=white&width=100&height=100' },
  { id: '185', text: 'Brushing teeth', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:toothbrush.svg?color=white&width=100&height=100' },
  { id: '186', text: 'Combing hair', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-getting-haircut.svg?color=white&width=100&height=100' },
  { id: '187', text: 'Getting dressed', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:t-shirt.svg?color=white&width=100&height=100' },
  { id: '188', text: 'Taking a bath', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-taking-bath.svg?color=white&width=100&height=100' },
  { id: '189', text: 'Washing hands', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:washing-hands.svg?color=white&width=100&height=100' },
  { id: '190', text: 'Cooking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cooking.svg?color=white&width=100&height=100' },
  { id: '191', text: 'Cleaning', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:broom.svg?color=white&width=100&height=100' },
  { id: '192', text: 'Reading', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:open-book.svg?color=white&width=100&height=100' },
  { id: '193', text: 'Writing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:writing-hand.svg?color=white&width=100&height=100' },
  { id: '194', text: 'Drawing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:artist-palette.svg?color=white&width=100&height=100' },
  { id: '195', text: 'Painting', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:artist-palette.svg?color=white&width=100&height=100' },
  { id: '196', text: 'Cutting', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:scissors.svg?color=white&width=100&height=100' },
  { id: '197', text: 'Gluing', categoryId: 'family', svgData: 'https://api.iconify.design/noto:glue.svg?color=white&width=100&height=100' },
  { id: '198', text: 'Talking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:speech-balloon.svg?color=white&width=100&height=100' },
  { id: '199', text: 'Listening', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:ear.svg?color=white&width=100&height=100' },
  { id: '200', text: 'Thinking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:thinking-face.svg?color=white&width=100&height=100' },
  { id: '201', text: 'Running', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-running.svg?color=white&width=100&height=100' },
  { id: '202', text: 'Walking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-walking.svg?color=white&width=100&height=100' },
  { id: '203', text: 'Jumping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-jumping.svg?color=white&width=100&height=100' },
  { id: '204', text: 'Hopping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:rabbit.svg?color=white&width=100&height=100' },
  { id: '205', text: 'Skipping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-skipping.svg?color=white&width=100&height=100' },
  { id: '206', text: 'Dancing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-dancing.svg?color=white&width=100&height=100' },
  { id: '207', text: 'Spinning', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:dizzy.svg?color=white&width=100&height=100' },
  { id: '208', text: 'Twirling', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sparkles.svg?color=white&width=100&height=100' },
  { id: '209', text: 'Crawling', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:baby.svg?color=white&width=100&height=100' },
  { id: '210', text: 'Climbing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-climbing.svg?color=white&width=100&height=100' },
  { id: '211', text: 'Swimming', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-swimming.svg?color=white&width=100&height=100' },
  { id: '212', text: 'Flying', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-in-manual-wheelchair.svg?color=white&width=100&height=100' },
  { id: '213', text: 'Sliding', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-sledding.svg?color=white&width=100&height=100' },
  { id: '214', text: 'Swinging', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-on-swings.svg?color=white&width=100&height=100' },
  { id: '215', text: 'Balancing', categoryId: 'family', svgData: 'https://api.iconify.design/noto:person-balancing.svg?color=white&width=100&height=100' },
  { id: '216', text: 'Marching', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-walking.svg?color=white&width=100&height=100' },
  { id: '217', text: 'Tiptoing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:ballet-shoes.svg?color=white&width=100&height=100' },
  { id: '218', text: 'Stretching', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-in-lotus-position.svg?color=white&width=100&height=100' },
  { id: '219', text: 'Bending', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-bowing.svg?color=white&width=100&height=100' },
  { id: '220', text: 'Reaching', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:raising-hands.svg?color=white&width=100&height=100' },
  { id: '221', text: 'Clapping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:clapping-hands.svg?color=white&width=100&height=100' },
  { id: '222', text: 'Stomping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:leg.svg?color=white&width=100&height=100' },
  { id: '223', text: 'Kicking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:foot.svg?color=white&width=100&height=100' },
  { id: '224', text: 'Throwing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:person-playing-handball.svg?color=white&width=100&height=100' },
  { id: '225', text: 'Catching', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:baseball.svg?color=white&width=100&height=100' },
  { id: '226', text: 'Smiling', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:smiling-face.svg?color=white&width=100&height=100' },
  { id: '227', text: 'Laughing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:rolling-on-the-floor-laughing.svg?color=white&width=100&height=100' },
  { id: '228', text: 'Giggling', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:grinning-face.svg?color=white&width=100&height=100' },
  { id: '229', text: 'Crying', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:crying-face.svg?color=white&width=100&height=100' },
  { id: '230', text: 'Yawning', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:yawning-face.svg?color=white&width=100&height=100' },
  { id: '231', text: 'Sneezing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:sneezing-face.svg?color=white&width=100&height=100' },
  { id: '232', text: 'Coughing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:face-with-open-mouth.svg?color=white&width=100&height=100' },
  { id: '233', text: 'Waving', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:waving-hand.svg?color=white&width=100&height=100' },
  { id: '234', text: 'Hugging', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:people-hugging.svg?color=white&width=100&height=100' },
  { id: '235', text: 'Kissing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:kissing-face.svg?color=white&width=100&height=100' },
  { id: '236', text: 'Blowing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:face-blowing-a-kiss.svg?color=white&width=100&height=100' },
  { id: '237', text: 'Whistling', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:hushed-face.svg?color=white&width=100&height=100' },
  { id: '238', text: 'Singing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:microphone.svg?color=white&width=100&height=100' },
  { id: '239', text: 'Whispering', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:shushing-face.svg?color=white&width=100&height=100' },
  { id: '240', text: 'Shouting', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:face-with-open-mouth.svg?color=white&width=100&height=100' },
  { id: '241', text: 'Barking', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:dog.svg?color=white&width=100&height=100' },
  { id: '242', text: 'Meowing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:cat.svg?color=white&width=100&height=100' },
  { id: '243', text: 'Roaring', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:lion.svg?color=white&width=100&height=100' },
  { id: '244', text: 'Chirping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:bird.svg?color=white&width=100&height=100' },
  { id: '245', text: 'Buzzing', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:honeybee.svg?color=white&width=100&height=100' },
  { id: '246', text: 'Digging', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:shovel.svg?color=white&width=100&height=100' },
  { id: '247', text: 'Planting', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:seedling.svg?color=white&width=100&height=100' },
  { id: '248', text: 'Watering', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:watering-can.svg?color=white&width=100&height=100' },
  { id: '249', text: 'Building', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:building-construction.svg?color=white&width=100&height=100' },
  { id: '250', text: 'Helping', categoryId: 'family', svgData: 'https://api.iconify.design/fluent-emoji:handshake.svg?color=white&width=100&height=100' },
];

export const getCardsByCategory = (categoryId: string): Card[] => {
  switch (categoryId) {
    case 'animals':
      return ANIMAL_CARDS;
    case 'family':
      return FAMILY_CARDS;
    default:
      return [];
  }
};

export const shuffleCards = (cards: Card[]): Card[] => {
  const shuffled = [...cards];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};
